Estruturação do projeto
SouJunior/linkedin-frontend pull request #30
Opened 2022-08-29 19:44 UTC by allbertuu

Medidas feitas até agora em geral.

2022-08-29 20:16 UTC, nesantana requested changes

2022-08-29 20:16 UTC, nesantana commented on src/components/styles/Container.styled.ts
> +  & {
Esse & não é necessário.

Tem um porque ter utilizado?

2022-08-29 20:16 UTC, nesantana commented on src/components/styles/Container.styled.ts
> +    }
Mesmo caso do comentário anterior

2022-08-29 20:16 UTC, nesantana commented on src/components/styles/Container.styled.ts
> +    }
Mesmo caso do comentário anterior

2022-08-29 20:16 UTC, nesantana commented on src/components/styles/Container.styled.ts
> +    }
Mesmo caso do comentário anterior

2022-08-29 20:16 UTC, nesantana commented on src/components/styles/Container.styled.ts
> +    }
Mesmo caso do comentário anterior

2022-08-29 20:27 UTC, allbertuu commented on src/components/styles/Container.styled.ts
> +  & {
Não tem. É apenas para ficar claro que a referência é ao pai.

2022-08-30 00:40 UTC, nesantana approved these changes

2022-08-30 00:40 UTC, merged