feat: add Input component
SouJunior/linkedin-frontend pull request #34
Opened 2022-09-09 20:00 UTC by allbertuu

Adicionado componente Input à pasta `component`, com as devidas estilizações do protótipo.

2022-09-09 20:36 UTC, SilviaLTeixeira reviewed
Pra mim parece estar ok

2022-09-12 18:24 UTC, allbertuu commented
Adicionado suporte para ícones dentro do componente Input. 
@nesantana olha pra mim, sei que a lógica dá pra ser melhorada, mas deixei ele bem completinho e inteligente até onde deu, seguindo o protótipo e safe-cases para um input.

2022-09-12 19:02 UTC, nesantana requested changes

2022-09-12 19:02 UTC, nesantana commented on src/components/InputWrapper.tsx
> +const InputWrapper = ({ children }: any) => {
Quando falamos de component, a sintax correta é:

`
const InputWrapper: React.FC<any> = ({ children }) => {}
`

2022-09-12 19:14 UTC, allbertuu commented on src/components/InputWrapper.tsx
> +const InputWrapper = ({ children }: any) => {
interessante, okay.
irei fazer.

2022-09-14 15:07 UTC, allbertuu commented on src/components/InputWrapper.tsx
> +    top: 55%;
@nesantana admito que isso foi uma gambiarra. Mas não pensei em nd diferente disso, pois tags inputs não podem receber chidrens... quanto mais um ReactNode.

2022-09-14 17:11 UTC, nesantana requested changes

2022-09-14 17:11 UTC, nesantana commented on src/components/InputWrapper.tsx
> +const InputWrapper: React.FC<any> = ({ children }: InputWrapperProps) => {
```suggestion
const InputWrapper: React.FC<InputWrapperProps> = ({ children }) => {
```

2022-09-14 19:53 UTC, SilviaLTeixeira approved these changes

2022-09-14 19:55 UTC, nesantana requested changes

2022-09-14 19:55 UTC, nesantana commented on src/components/InputWrapper.tsx
> +import styled from "styled-components";
Precisa importar o React.

```suggestion
import React from "react";
import styled from "styled-components";
```

2022-09-14 21:06 UTC, nesantana approved these changes

2022-09-14 21:06 UTC, merged