Página de Denúncias
SouJunior/linkedin-frontend pull request #45
Opened 2022-09-17 18:00 UTC by CarlosJunioor

Criando a página de Report.

2022-09-28 15:34 UTC, allbertuu requested changes
Até onde consegui revisar no momento, é isso.
Depois podem dar uma olhada melhor, @nesantana e o Gustavo Roberto?

2022-09-28 15:34 UTC, allbertuu commented on src/App.tsx
> +        <Route index element={<Report />} />
A página de Login é o ponto principal da aplicação, o `index` route.
```suggestion
        <Route index element={<Login/>} />
```

2022-09-28 15:34 UTC, allbertuu commented on src/App.tsx
>            <Route path="insertjobs" element={<InsertJobs />} />
@CarlosJunioor A página de Report vai aqui. 
@nesantana a página vai temporariamente sem query params ou já se consegue ser feito uma rota dinâmica para denúncias?

2022-09-28 15:34 UTC, allbertuu commented on src/components/HeaderReport.tsx
> +import { RiArrowLeftLine as ArrowLeftIcon } from "react-icons/ri";
Remover todo esse componente.
O Header é modular e só precisa ser chamado e polimorfizado por props.

2022-09-28 15:34 UTC, allbertuu commented on yarn.lock
> +"react-scripts@^5.0.1":
Mesma coisa do package.json

2022-09-29 09:28 UTC, CarlosJunioor commented on package.json
> +    "react-scripts": "^5.0.1",
Qual a diferença e possuir o ^ ou não?

2022-09-29 09:56 UTC, allbertuu commented on package.json
> +    "react-scripts": "^5.0.1",
é um indicador pro package.json quando instalar essa dependência, a versão instalada esteja >=5.0.1 e <6.0.0.
Acredito que seria bom tirar, mas não é nada que atrapalhe a gente.

2022-09-29 10:10 UTC, CarlosJunioor commented on package.json
> +    "react-scripts": "^5.0.1",
ok ja resolvi

2022-09-29 11:38 UTC, allbertuu commented on src/pages/Report.tsx
> +  const [count, setCount] = useState(0);
Esse estado está sendo usado?

2022-09-29 11:38 UTC, allbertuu commented on src/pages/Report.tsx
> +import Header from "../components/HeaderReport";
Já existe um Header genérico que muda baseado em props `title` e `backTo`
```suggestion
```

2022-10-01 01:46 UTC, gustavoaroberto requested changes
O código está excelente, só precisa fazer alguns pequenos ajustes para ficar perfeito. (Remover os espaçamentos adicionais em diversas classes css do componente [deixei alguns exemplos feitos, mas seria interessante verificar o componente inteiro!])

2022-10-01 01:46 UTC, gustavoaroberto commented on src/pages/Report.tsx
> +              <span className="text-sm text-gray-600 absolute bottom-4 right-4    ">
Remover o espaçamento a mais depois do nome da classe
```suggestion
              <span className="text-sm text-gray-600 absolute bottom-4 right-4">
```

2022-10-01 01:46 UTC, gustavoaroberto commented on src/pages/Report.tsx
> +                Denúnciar
Denunciar não possui acento!
```suggestion
                Denunciar
```

2022-10-01 01:46 UTC, gustavoaroberto commented on src/pages/Report.tsx
> +              <button className="bg-transparent border border-blue-600  py-3 px-6 md:flex md:flex-1 md:w-auto w-full rounded md:mr-0 mr-0  text-blue-600 flex flex-1 justify-center items-center">
Espaçamento a mais entre as classes, por favor remover
```suggestion
              <button className="bg-transparent border border-blue-600 py-3 px-6 md:flex md:flex-1 md:w-auto w-full rounded md:mr-0 mr-0 text-blue-600 flex flex-1 justify-center items-center">
```

2022-10-01 01:46 UTC, gustavoaroberto commented on src/pages/Report.tsx
> +                id=""
Se o id não possui valor, não há necessidade de adicionar a propriedade ao elemento!
```suggestion

```

2022-10-01 01:46 UTC, gustavoaroberto commented on src/pages/Report.tsx
> +                className="px-4 border py-4 rounded-lg mt-5 min-h-[527px] resize-none w-full "
Não é necessário espaçamento no final da última classe!
```suggestion
                className="px-4 border py-4 rounded-lg mt-5 min-h-[527px] resize-none w-full"
```

2022-10-01 01:46 UTC, gustavoaroberto commented on src/pages/Report.tsx
> +                  <h4 className="font-semibold  text-gray-600">
Remover espaçamento duplo entre as classes!
```suggestion
                  <h4 className="font-semibold text-gray-600">
```

2022-10-01 01:46 UTC, gustavoaroberto commented on src/pages/Report.tsx
> +                  <p className="font-medium  text-gray-600 my-3">
Remover espaçamento duplo entre as classes!
```suggestion
                  <p className="font-medium text-gray-600 my-3">
```

2022-10-01 01:46 UTC, gustavoaroberto commented on src/pages/Report.tsx
> +                  <p className="font-medium  text-gray-600 my-3">
Remover espaçamento duplo entre as classes!
```suggestion
                  <p className="font-medium text-gray-600 my-3">
```

2022-10-01 01:46 UTC, gustavoaroberto commented on src/pages/Report.tsx
> +                  <p className="font-medium  text-gray-600 my-3">
Remover espaçamento duplo entre as classes!
```suggestion
                  <p className="font-medium text-gray-600 my-3">
```

2022-10-01 01:46 UTC, gustavoaroberto commented on src/pages/Report.tsx
> +                  <p className="font-medium  text-gray-600 my-3">
```suggestion
                  <p className="font-medium text-gray-600 my-3">
```

2022-10-01 01:46 UTC, gustavoaroberto commented on src/pages/Report.tsx
> +                  <p className="font-medium  text-gray-600 my-3">
```suggestion
                  <p className="font-medium text-gray-600 my-3">
```

2022-10-05 11:50 UTC, allbertuu requested changes
- Algumas mudanças nas classes, repetindo classes para tamanhos de telas diferentes. O Tailwind trabalha com min-width nas querys, logo cada classe se refere a qualquer tamanho de tela, a menos que uma outra maior seja indicada (md, lg, etc) e a sobreescreva.
- Refatorar states, o `count` seria desnecessário.

2022-10-05 11:50 UTC, allbertuu commented on src/pages/Report.tsx
> +              <button className="bg-red-600 md:flex md:flex-1 md:w-auto w-full hover:bg-red-700 text-white py-3 px-6 font-semibold rounded md:mb-0 mb-4 md:mb-0 flex flex-1 justify-center items-center
Remover classe repetida.
Remover classes iguais para `md` e < md
```suggestion
              <button className="bg-red-600 md:w-auto w-full hover:bg-red-700 text-white py-3 px-6 font-semibold rounded md:mb-0 mb-4 flex flex-1 justify-center items-center md:mr-4 mr-0">
```

2022-10-05 11:50 UTC, allbertuu commented on src/pages/Report.tsx
> +              <button className="bg-transparent border border-blue-600 py-3 px-6 md:flex md:flex-1 md:w-auto w-full rounded md:mr-0 mr-0 text-blue-600 flex flex-1 justify-center items-center">
Remover classes iguais para `md `e < md
```suggestion
              <button className="bg-transparent border border-blue-600 py-3 px-6 md:w-auto w-full rounded mr-0 text-blue-600 flex flex-1 justify-center items-center">
```

2022-10-05 11:50 UTC, allbertuu commented on src/pages/Report.tsx
> +              <div className="bg-[#FCFCFC] border rounded-lg mt-6 py-4 px-6 flex items-center justify-between hidden md:flex">
Remover classes iguais para `md `e < md
```suggestion
              <div className="bg-[#FCFCFC] border rounded-lg mt-6 py-4 px-6 flex items-center justify-between hidden">
```

2022-10-05 11:50 UTC, allbertuu commented on src/pages/Report.tsx
> +  const [count, setCount] = useState(0);
Apagar state desnecessário. (explicação lá embaixo)
```suggestion
```

2022-10-05 11:50 UTC, allbertuu commented on src/pages/Report.tsx
> +    setCount(e.target.value.length);
Apagar state desnecessário. (explicação lá embaixo)
```suggestion
```

2022-10-05 11:50 UTC, allbertuu commented on src/pages/Report.tsx
> +        <Outlet />
Qual a utilidade desse `Outlet` component estar aqui nessa parte do código?

2022-10-05 11:50 UTC, allbertuu commented on src/pages/Report.tsx
> +                {count}/{MAX_LENGTH}
Utilizar a própria string `message` para medir o tamanho da mensagem (caracteres), ao invés de outro state chamado `count`.
```suggestion
                {message.length}/{MAX_LENGTH}
```

2022-10-05 14:15 UTC, CarlosJunioor commented on src/pages/Report.tsx
> +              <button className="bg-red-600 md:flex md:flex-1 md:w-auto w-full hover:bg-red-700 text-white py-3 px-6 font-semibold rounded md:mb-0 mb-4 md:mb-0 flex flex-1 justify-center items-center
done

2022-10-05 14:16 UTC, CarlosJunioor commented on src/pages/Report.tsx
> +              <button className="bg-transparent border border-blue-600 py-3 px-6 md:flex md:flex-1 md:w-auto w-full rounded md:mr-0 mr-0 text-blue-600 flex flex-1 justify-center items-center">
done

2022-10-05 14:16 UTC, CarlosJunioor commented on src/pages/Report.tsx
> +              <div className="bg-[#FCFCFC] border rounded-lg mt-6 py-4 px-6 flex items-center justify-between hidden md:flex">
done

2022-10-05 14:18 UTC, CarlosJunioor commented on src/pages/Report.tsx
> +  const [count, setCount] = useState(0);
done

2022-10-05 14:18 UTC, CarlosJunioor commented on src/pages/Report.tsx
> +    setCount(e.target.value.length);
done

2022-10-05 14:18 UTC, CarlosJunioor commented on src/pages/Report.tsx
> +        <Outlet />
foi engano meu.

2022-10-05 14:19 UTC, CarlosJunioor commented on src/pages/Report.tsx
> +                {count}/{MAX_LENGTH}
done

2022-10-05 14:32 UTC, allbertuu commented on src/pages/Report.tsx
> +                {count}/{MAX_LENGTH}
✅

2022-10-05 14:32 UTC, allbertuu commented on src/pages/Report.tsx
> +    setCount(e.target.value.length);
✅

2022-10-05 14:32 UTC, allbertuu commented on src/pages/Report.tsx
> +  const [count, setCount] = useState(0);
✅

2022-10-05 14:39 UTC, allbertuu requested changes
Outros apontamentos.

2022-10-05 14:39 UTC, allbertuu commented on src/pages/Report.tsx
> +      <Header title="Central de denúncias" backTo="component"/>
Deixa esse backTo sem rota, pois ainda precisamos alinhar isso com a equipe de UI/UX
```suggestion
      <Header title="Central de denúncias" backTo=""/>
```

2022-10-05 14:39 UTC, allbertuu commented on src/pages/Report.tsx
> +  function handleMessage(e: any): void {
Para ganho de performance, transformar essa `function` em arrow function. 
> Não precisa inserir `void` como retorno da função.
> Adicionar `ChangeEvent` type e importa-lo do `React`
```suggestion
  const handleMessage = (e: ChangeEvent<HTMLTextAreaElement>) => {
```

2022-10-07 12:21 UTC, allbertuu commented on src/pages/Report.tsx
> +      <Header title="Central de denúncias" backTo="component"/>
@CarlosJunioor atenção a esses comentários.

2022-10-07 12:21 UTC, allbertuu commented on src/pages/Report.tsx
> +  function handleMessage(e: any): void {
@CarlosJunioor atenção a esses comentários.

2022-10-07 17:41 UTC, CarlosJunioor commented on src/pages/Report.tsx
> +      <Header title="Central de denúncias" backTo="component"/>
ta feiot

2022-10-07 17:41 UTC, CarlosJunioor commented on src/pages/Report.tsx
> +  function handleMessage(e: any): void {
ta feito

2022-10-07 18:32 UTC, allbertuu requested changes
### Sobre commits de correção em PRs
@CarlosJunioor Você também pode fazer commits pontuais de correção, ex.: fix: `fix text on XXX component`. Ao invés de acoplar mudanças em um commit generalizado, como `fixed: couple of issues`. 
Lembre-se que os commits realizados nesse PR, perduram no código base, pois são mergeados no histórico principal de commits do repo da SouJunior Frontend. Tendo isso como base, para uma melhor cooperação entre a equipe, saber exatamente qual mudança ocorreu em um arquivo específico é em minha opinião fundamental para mantermos a manutibilidade e facilidade de pesquisa em mudanças singulares, além de prevenir a criação de bugs e facilitar o code review.
### Sobre a revisão que fiz agora
Apenas importar o tipo do evento de dentro do React para habilitar o TypeScript no parâmetro e escopo da função.

_Grato, Alberto Santos - Dev. Frontend._

2022-10-07 18:32 UTC, allbertuu commented on src/pages/Report.tsx
> +  const handleMessage = (e: ChangeEvent<HTMLTextAreaElement>) => {
Deve-se importar esse tipo do React. Nesse caso, ali na linha 1 ficará assim:
`import React, { useState, ChangeEvent } from "react";`

2022-10-07 18:33 UTC, allbertuu commented on src/pages/Report.tsx
> +      <Header title="Central de denúncias" backTo="component"/>
Good job!

2022-10-07 18:33 UTC, allbertuu commented on src/pages/Report.tsx
> +  function handleMessage(e: any): void {
Good job!

2022-10-07 18:36 UTC, CarlosJunioor commented on src/pages/Report.tsx
> +  const handleMessage = (e: ChangeEvent<HTMLTextAreaElement>) => {
done!

2022-10-07 18:38 UTC, allbertuu commented on src/pages/Report.tsx
> +  const handleMessage = (e: ChangeEvent<HTMLTextAreaElement>) => {
Good job!

2022-10-07 18:38 UTC, allbertuu approved these changes

2022-10-07 18:38 UTC, merged