component extendedfooter created
SouJunior/linkedin-frontend pull request #48
Opened 2022-09-27 20:40 UTC by FilipeLeoni

Criação do componente extendedfooter

2022-09-28 11:52 UTC, allbertuu requested changes
Code review por @allbertuu.
@nesantana acha uma boa não deixar esse lock.json passar pra main?

2022-09-28 11:52 UTC, allbertuu commented on src/components/ExtendedFooter.tsx
> +
Remover espaço em branco
```suggestion
```

2022-09-28 11:52 UTC, allbertuu commented on src/components/ExtendedFooter.tsx
> +                    <p className="text-gray-darker text-sm mt-px">O SouJunior ajuda você a encontrar um lugar de<br/> destaque
Seria legal usar o Prettier nos códigos. Se trata de uma ferramenta, extensão do VS Code tbm, que formata os códigos.
É importante os códigos seguirem um padrão, e eu e a @SilviaLTeixeira já utilizamos nos já existentes.
Essa sugestão também vale para o @CarlosJunioor .

2022-09-28 11:52 UTC, allbertuu commented on tailwind.config.js
> +        canada : ['Radio Canada', 'sans-serif']
É uma boa prática adicionar props como `fontFamily` no Tema (principal), pois assim ocorre a sobreescrita no tema como um todo.
Acima do `extend` ali, só mover esse bloco (objeto) com as alterações que fiz pra lá. Se tiver dúvidas, só falar aqui.
```suggestion
        sans: ["Inter", "sans-serif"],
        canada : ['Radio Canada', 'sans-serif'],
```

2022-09-29 18:58 UTC, allbertuu approved these changes
Parabéns. ✨🚀

2022-10-01 01:36 UTC, gustavoaroberto approved these changes

2022-10-01 01:49 UTC, gustavoaroberto commented on src/components/ExtendedFooter.tsx
> +          <h2 className="font-semibold text-gray-darker text-[25px] mt-2 ">
Remover o espaçamento após a última classe
```suggestion
          <h2 className="font-semibold text-gray-darker text-[25px] mt-2">
```

2022-10-04 14:55 UTC, merged